CREATE DATABASE VENDAS;
CREATE TABLE PRODUTOS(
    ID_PRODUTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DECRICAO VARCHAR(30),
    ESTOQUE_PRODUTO INT NOT NULL,
    PRECO_PRODUTO DOUBLE
    );
   
 CREATE TABLE VENDA(
 
    ID_VENDA INT NOT  NULL PRIMARY KEY AUTO_INCREMENT,
    NUMERO_VENDA INT NOT NULL,
    ID_PRODUTO INT,
    QUANTIDADE INT
   
 );
 
 INSERT INTO PRODUTOS (DECRICAO, ESTOQUE_PRODUTO, PRECO_PRODUTO) VALUE ("CUSCUZ", 35, 4);
 INSERT INTO PRODUTOS (DECRICAO, ESTOQUE_PRODUTO, PRECO_PRODUTO) VALUE ("ARROZ", 23, 3);
 INSERT INTO PRODUTOS (DECRICAO, ESTOQUE_PRODUTO, PRECO_PRODUTO) VALUE ("FEIJAO", 32, 2);
 INSERT INTO PRODUTOS (DECRICAO, ESTOQUE_PRODUTO, PRECO_PRODUTO) VALUE ("FARINHA", 50, 5);

 SELECT*FROM PRODUTOS;
 SELECT*FROM VENDA;
 
 INSERT INTO VENDA(NUMERO_VENDA, ID_PRODUTO, QUANTIDADE) VALUES(10,4,5);

 DELIMITER $$
 CREATE TRIGGER ATUALIZAR_ESTOQUE AFTER INSERT
 ON VENDA
 FOR EACH ROW 
 BEGIN 
 
 UPDATE PRODUTOS SET ESTOQUE_PRODUTO = ESTOQUE_PRODUTO - NEW.QUANTIDADE WHERE ID_PRODUTO = NEW.ID_PRODUTO;
 
 END $$
 
 DELIMITER ; 
 
 
DELIMITER $$
CREATE TRIGGER CANCELAR_VENDA AFTER INSERT
ON VENDA
FOR EACH ROW
BEGIN

UPDATE PRODUTOS SET ESTOQUE_PRODUTO = ESTOQUE_PRODUTO - NEW.QUANTIDADE WHERE ID_PRODUTO = NEW.ID_PRODUTO; 

END $$
DELIMITER ;
 
 